name: Update README cards

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&count_private=true&theme=catppuccin_mocha
          path: cards/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=catppuccin_mocha&langs_count=3
          path: cards/langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch top repositories
        id: fetch_top
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TOP_REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/${{ github.repository_owner }}/repos?per_page=100" \
            | jq 'sort_by(.stargazers_count) | reverse | map(select((.fork | not) and (.archived | not)))')
          REPO_1=$(echo "$TOP_REPOS" | jq -r '.[0].name')
          REPO_2=$(echo "$TOP_REPOS" | jq -r '.[1].name')
          echo "REPO_1=$REPO_1" >> $GITHUB_OUTPUT
          echo "REPO_2=$REPO_2" >> $GITHUB_OUTPUT

      - name: Generate Top Project \#1 Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=${{ steps.fetch_top.outputs.REPO_1 }}&show_icons=true&theme=catppuccin_mocha&description_lines_count=2
          path: assets/cards/project-1.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Project \#2 Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=${{ steps.fetch_top.outputs.REPO_2 }}&show_icons=true&theme=catppuccin_mocha&description_lines_count=2
          path: assets/cards/project-2.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/cards/*.svg
          git commit -m "chore: update cards" || echo "No changes to commit"
          git push